<template>
  <section class="panel">
    <header class="panel__header"><div><p class="eyebrow">Movimentações</p><h2 class="panel__title">Pagamentos</h2></div></header>
    <div class="payment-filters">
      <input v-model="filters.query" class="field" placeholder="Nome ou descrição" @keydown.enter.prevent="load(1)" />
      <label><span>Vencimento inicial</span><input v-model="filters.initial" class="field" type="date" /></label>
      <label><span>Vencimento final</span><input v-model="filters.final" class="field" type="date" /></label>
      <div class="status-toggle"><button :class="filters.aberto ? 'active' : ''" @click="toggleStatus('aberto')">Aberto</button><button :class="filters.quitado ? 'active paid' : ''" @click="toggleStatus('quitado')">Quitado</button></div>
      <button class="secondary-button" @click="load(1)">Aplicar filtros</button>
    </div>
    <p v-if="error" class="feedback feedback--error">{{ error }}</p>
    <div class="movement-summary"><div><small>Total do período</small><strong>{{ money(result.total_valor) }}</strong></div><div><small>Em aberto</small><strong>{{ money(result.total_aberto) }}</strong></div><div><small>Pago</small><strong>{{ money(result.total_pago) }}</strong></div></div>
    <div class="table-wrap"><table class="data-table data-table--cadastro"><thead><tr><th>Vencimento</th><th>Nome / descrição</th><th>Documento</th><th>Telefone</th><th>Tipo</th><th>Valor</th><th>Pago</th><th>Aberto</th><th>Status</th><th>Ações</th></tr></thead><tbody>
      <tr v-if="loading"><td colspan="10">Carregando pagamentos...</td></tr><tr v-else-if="!result.items.length"><td colspan="10">Nenhuma parcela encontrada.</td></tr>
      <tr v-for="item in result.items" :key="item.parcela_id" class="data-table__row"><td>{{ date(item.vencimento) }}</td><td><strong>{{ item.pessoa_nome }}</strong><br><small>{{ item.descricao }}</small></td><td>{{ item.documento || '-' }}</td><td>{{ item.telefone || '-' }}</td><td>{{ type(item.pessoa_tipo) }}</td><td>{{ money(item.valor_total) }}</td><td>{{ money(item.valor_pago) }}</td><td>{{ money(item.saldo_pagar) }}</td><td><span :class="['pill', item.quitado ? 'pill--success' : 'pill--warning']">{{ item.quitado ? `QUITADO ${item.data_pagamento ? 'EM ' + date(item.data_pagamento) : ''}` : 'ABERTO' }}</span></td><td class="actions-cell"><button v-if="!item.quitado" class="secondary-button action-pay" @click="openPay(item)">Pagar</button><button class="icon-action" title="Alterar conta a pagar" @click="edit(item.conta_pagar_id)">✎</button></td></tr>
    </tbody></table></div>
    <footer class="pagination-compact"><div class="pagination-compact__status">{{ range }}</div><div class="pagination-compact__actions"><button class="pagination-compact__button" :disabled="result.page<=1" @click="load(1)">«</button><button class="pagination-compact__button" :disabled="result.page<=1" @click="load(result.page-1)">‹</button><button class="pagination-compact__button" :disabled="result.page>=pages" @click="load(result.page+1)">›</button><button class="pagination-compact__button" :disabled="result.page>=pages" @click="load(pages)">»</button></div></footer>
    <div v-if="payment" class="modal-backdrop" @click.self="payment=null"><section class="modal-card pay-modal"><h3>Registrar pagamento</h3><p>{{ payment.pessoa_nome }} · {{ payment.descricao }}</p><label class="field-group"><span>Valor pago</span><input v-model.number="payValue" class="field" min="0.01" step="0.01" type="number" /></label><label class="field-group"><span>Data do pagamento</span><input v-model="payDate" class="field" type="date" /></label><div class="form-actions"><button class="ghost-button" @click="payment=null">Cancelar</button><button class="primary-button" @click="confirmPay">Pagar</button></div></section></div>
  </section>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import type { PaymentMovementItem, PaymentMovementListResponse } from '@/models/accountsPayable'
import { listPaymentMovements, registerAccountsPayablePayment } from '@/services/accountsPayableService'
import { errorAlert, successAlert } from '@/services/alertService'
const formatDate=(value:Date)=>{const timezoneOffset=value.getTimezoneOffset()*60000;return new Date(value.getTime()-timezoneOffset).toISOString().slice(0,10)};const router=useRouter(); const filters=reactive({query:'',initial:'',final:'',aberto:true,quitado:false});function applySuggestedDates(){const today=new Date();const finalDate=new Date(today);finalDate.setDate(finalDate.getDate()+7);filters.initial=formatDate(today);filters.final=formatDate(finalDate)}applySuggestedDates(); const loading=ref(false); const error=ref(''); const payment=ref<PaymentMovementItem|null>(null); const payValue=ref(0); const payDate=ref(formatDate(new Date())); const result=ref<PaymentMovementListResponse>({items:[],total:0,page:1,page_size:10,total_valor:0,total_pago:0,total_aberto:0})
const pages=computed(()=>Math.max(1,Math.ceil(result.value.total/result.value.page_size))); const range=computed(()=>result.value.total?`${(result.value.page-1)*result.value.page_size+1}-${Math.min(result.value.page*result.value.page_size,result.value.total)} de ${result.value.total}`:'0-0 de 0')
async function load(page=result.value.page){loading.value=true;error.value='';try{result.value=await listPaymentMovements({page,page_size:10,query:filters.query.trim()||undefined,aberto:filters.aberto,quitado:filters.quitado,data_vencimento_inicial:filters.initial,data_vencimento_final:filters.final})}catch(e){error.value=e instanceof Error?e.message:'Falha ao carregar pagamentos.'}finally{loading.value=false}}
function toggleStatus(status:'aberto'|'quitado'){filters[status]=!filters[status];void load(1)}
function openPay(item:PaymentMovementItem){payment.value=item;payValue.value=item.saldo_pagar;payDate.value=new Date().toISOString().slice(0,10)} function edit(id:number){router.push({name:'accounts-payable-edit',params:{id}})} async function confirmPay(){if(!payment.value||payValue.value<=0)return;try{await registerAccountsPayablePayment(payment.value.parcela_id,{valor_pago:payValue.value,data_pagamento:payDate.value});payment.value=null;await load();await successAlert('Pagamento registrado.','update')}catch(e){await errorAlert(e instanceof Error?e.message:'Falha ao registrar pagamento.')}} const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0);const date=(v:string)=>new Intl.DateTimeFormat('pt-BR').format(new Date(`${v}T00:00:00`));const type=(v:string)=>({cliente:'Cliente',fornecedor:'Fornecedor',funcionario:'Funcionário'}[v]||v);onMounted(()=>void load(1))
</script>
<style scoped>
.payment-filters{display:grid;grid-template-columns:minmax(14rem,1.4fr) 10rem 10rem 14rem auto;gap:.7rem;align-items:end}.payment-filters label{display:grid;gap:4px;font-size:11px;font-weight:700;color:#5f6d78}.status-toggle{display:grid;grid-template-columns:1fr 1fr;min-height:34px;border:1px solid rgba(249,115,22,.24);border-radius:4px;overflow:hidden;background:rgba(249,115,22,.08)}.status-toggle button{border:0;background:transparent;text-transform:uppercase;font-weight:700;font-size:11px;cursor:pointer}.status-toggle button+button{border-left:1px solid rgba(249,115,22,.2)}.status-toggle .active,.status-toggle .paid{background:rgba(31,157,104,.14);color:#1b7f56}.movement-summary{display:flex;justify-content:flex-end;gap:1px;margin:1rem 0}.movement-summary div{display:grid;gap:2px;min-width:130px;padding:.6rem .8rem;background:#f8fafc;border:1px solid #e2e8f0}.movement-summary small{color:#64748b;font-size:10px;text-transform:uppercase}.movement-summary strong{color:#334155;font-size:14px}.action-pay{min-height:28px;padding:0 9px;margin-right:5px;font-size:11px}.pay-modal{max-width:360px}.pay-modal p{color:#64748b;font-size:.85rem}.pay-modal .field-group{display:grid;gap:4px;margin-top:10px;font-size:12px}@media(max-width:1050px){.payment-filters{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.payment-filters{grid-template-columns:1fr}.movement-summary{justify-content:stretch}.movement-summary div{flex:1;min-width:0}}
</style>
