from datetime import datetime

from sqlalchemy import BigInteger, Boolean, DateTime, ForeignKey, Integer, Numeric, String
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class Cliente(Base):
    __tablename__ = "clientes"

    clientes_id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True, index=True)
    nome: Mapped[str | None] = mapped_column(String(70), nullable=True, index=True)
    rg: Mapped[float | None] = mapped_column(Numeric(19, 0, asdecimal=False), nullable=True)
    cpf_cnpj: Mapped[str | None] = mapped_column(String(18), nullable=True, index=True)
    endereco: Mapped[str | None] = mapped_column(String(70), nullable=True)
    bairro_id: Mapped[int | None] = mapped_column(ForeignKey("bairros.bairro_id", ondelete="SET NULL"), nullable=True, index=True)
    cidade_id: Mapped[int | None] = mapped_column(BigInteger, ForeignKey("cidades.cidade_id", ondelete="SET NULL"), nullable=True, index=True)
    uf: Mapped[str | None] = mapped_column(String(2), ForeignKey("uf.uf", ondelete="SET NULL"), nullable=True, index=True)
    usuario_id: Mapped[int | None] = mapped_column(ForeignKey("usuarios.id", ondelete="SET NULL"), nullable=True, index=True)
    cnpj: Mapped[str | None] = mapped_column(String(18), nullable=True)
    telefone: Mapped[str | None] = mapped_column(String(15), nullable=True)
    celular01: Mapped[str | None] = mapped_column(String(15), nullable=True)
    celular02: Mapped[str | None] = mapped_column(String(15), nullable=True)
    flag_whatsapp: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    nao_enviar_whatsapp: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    email: Mapped[str | None] = mapped_column(String(150), nullable=True, index=True)
    limite_credito: Mapped[float | None] = mapped_column(Numeric(24, 6, asdecimal=False), nullable=True)
    debito_atual: Mapped[float | None] = mapped_column(Numeric(24, 6, asdecimal=False), nullable=True)
    prox_vencto: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    data_ultcompra: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    rg_ie: Mapped[str | None] = mapped_column(String(20), nullable=True)
    latitude: Mapped[str | None] = mapped_column(String(50), nullable=True)
    longitude: Mapped[str | None] = mapped_column(String(50), nullable=True)
    cep: Mapped[str | None] = mapped_column(String(9), nullable=True)
    nro: Mapped[str | None] = mapped_column(String(6), nullable=True)
    complemento: Mapped[str | None] = mapped_column(String(50), nullable=True)
    ativo: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    bloqueado: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    comissao_diferente: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    percent_comissao: Mapped[float | None] = mapped_column(Numeric(19, 4, asdecimal=False), nullable=True)
    naopagarcomissao: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    desativado: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    data_desat: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    contato_responsavel: Mapped[str | None] = mapped_column(String(50), nullable=True)
    endereco_responsavel: Mapped[str | None] = mapped_column(String(100), nullable=True)
    fone_responsavel: Mapped[str | None] = mapped_column(String(15), nullable=True)
    cel_responsavel: Mapped[str | None] = mapped_column(String(15), nullable=True)
    flag_whatsapp_responsavel: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    cep_responsavel: Mapped[str | None] = mapped_column(String(9), nullable=True)
    complemento_responsavel: Mapped[str | None] = mapped_column(String(50), nullable=True)
    uf_referencia: Mapped[str | None] = mapped_column(String(2), ForeignKey("uf.uf", ondelete="SET NULL"), nullable=True)
    cidade_ref_id: Mapped[int | None] = mapped_column(BigInteger, ForeignKey("cidades.cidade_id", ondelete="SET NULL"), nullable=True)
    bairro_id_responsavel: Mapped[int | None] = mapped_column(ForeignKey("bairros.bairro_id", ondelete="SET NULL"), nullable=True)
    nro_responsavel: Mapped[str | None] = mapped_column(String(6), nullable=True)
    uf_responsavel: Mapped[str | None] = mapped_column(String(2), ForeignKey("uf.uf", ondelete="SET NULL"), nullable=True)
    cidade_responsavel_id: Mapped[int | None] = mapped_column(BigInteger, ForeignKey("cidades.cidade_id", ondelete="SET NULL"), nullable=True)
    nacionalidade: Mapped[str | None] = mapped_column(String(40), nullable=True)
    estado_civil: Mapped[str | None] = mapped_column(String(30), nullable=True)
    profissao: Mapped[str | None] = mapped_column(String(30), nullable=True)
    mais_atrasada: Mapped[str | None] = mapped_column(String(10), nullable=True)
    parc_atrasadas: Mapped[int | None] = mapped_column(Integer, nullable=True)
    valor_atrasado: Mapped[float | None] = mapped_column(Numeric(19, 4, asdecimal=False), nullable=True)
    valor_em_aberto: Mapped[float | None] = mapped_column(Numeric(19, 4, asdecimal=False), nullable=True)
    parc_aberto: Mapped[int | None] = mapped_column(Integer, nullable=True)
    turno_cobranca: Mapped[str | None] = mapped_column(String(15), nullable=True)
    user_add: Mapped[int | None] = mapped_column(ForeignKey("usuarios.id", ondelete="SET NULL"), nullable=True)
    data_add: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    media_atraso_parcelas: Mapped[float | None] = mapped_column(Numeric(12, 6, asdecimal=False), nullable=True)
    media_atraso_contratos: Mapped[float | None] = mapped_column(Numeric(12, 6, asdecimal=False), nullable=True)
    regra_juros_id: Mapped[int | None] = mapped_column(BigInteger, ForeignKey("regras_juros.regra_juros_id", ondelete="SET NULL"), nullable=True, index=True)