from datetime import datetime

from sqlalchemy import JSON, BigInteger, Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class Parametro(Base):
    __tablename__ = "parametros"

    parametros_id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True, index=True)
    nome_fantasia: Mapped[str | None] = mapped_column(String(150), nullable=True, index=True)
    razao_social: Mapped[str | None] = mapped_column(String(150), nullable=True, index=True)
    endereco: Mapped[str | None] = mapped_column(String(70), nullable=True)
    bairrosid: Mapped[int | None] = mapped_column(ForeignKey("bairros.bairro_id", ondelete="SET NULL"), nullable=True, index=True)
    cep: Mapped[str | None] = mapped_column(String(9), nullable=True)
    nro: Mapped[int | None] = mapped_column(Integer, nullable=True)
    cnpj: Mapped[str | None] = mapped_column(String(18), nullable=True, index=True)
    uf: Mapped[str | None] = mapped_column(String(2), ForeignKey("uf.uf", ondelete="SET NULL"), nullable=True, index=True)
    cidade_id: Mapped[int | None] = mapped_column(ForeignKey("cidades.cidade_id", ondelete="SET NULL"), nullable=True, index=True)
    telefone1: Mapped[str | None] = mapped_column(String(17), nullable=True)
    flag_whatsapp_telefone1: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    telefone2: Mapped[str | None] = mapped_column(String(17), nullable=True)
    flag_whatsapp_telefone2: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    e_mail: Mapped[str | None] = mapped_column(String(200), nullable=True, index=True)
    responsavel: Mapped[str | None] = mapped_column(String(120), nullable=True)
    complemento: Mapped[str | None] = mapped_column(String(50), nullable=True)
    cpf: Mapped[str | None] = mapped_column(String(14), nullable=True)
    rg: Mapped[str | None] = mapped_column(String(25), nullable=True)
    cidade_id_responsavel: Mapped[int | None] = mapped_column(ForeignKey("cidades.cidade_id", ondelete="SET NULL"), nullable=True)
    bairro_id_responsavel: Mapped[int | None] = mapped_column(ForeignKey("bairros.bairro_id", ondelete="SET NULL"), nullable=True)
    uf_responsavel: Mapped[str | None] = mapped_column(String(2), ForeignKey("uf.uf", ondelete="SET NULL"), nullable=True)
    estado_civil: Mapped[str | None] = mapped_column(String(30), nullable=True)
    nacionalidade: Mapped[str | None] = mapped_column(String(40), nullable=True)
    endereco_responsavel: Mapped[str | None] = mapped_column(String(80), nullable=True)
    emitir_sons: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    score_valor_inicial: Mapped[int] = mapped_column(Integer, nullable=False, default=1000)
    score_pontos_atraso_parcela: Mapped[int] = mapped_column(Integer, nullable=False, default=15)
    score_pontos_atraso_quitacao_contrato: Mapped[int] = mapped_column(Integer, nullable=False, default=30)
    score_pontos_pagamento_em_dia: Mapped[int] = mapped_column(Integer, nullable=False, default=5)
    score_pontos_quitacao_em_dia: Mapped[int] = mapped_column(Integer, nullable=False, default=20)
    score_pontos_negociacao: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    score_atualizacao_automatica: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    score_agendamentos: Mapped[list[dict[str, object]]] = mapped_column(JSON, nullable=False, default=list)
    score_atualizacao_ultima_execucao: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    score_atualizacao_proxima_execucao: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    score_ultima_execucao_sucesso: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    score_ultimo_erro: Mapped[str | None] = mapped_column(Text, nullable=True)
    whatsapp_cobranca_automatica: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    whatsapp_agendamentos: Mapped[list[dict[str, object]]] = mapped_column(JSON, nullable=False, default=list)
    whatsapp_cobranca_ultima_execucao: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    whatsapp_cobranca_proxima_execucao: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    whatsapp_ultima_execucao_sucesso: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    whatsapp_ultimo_erro: Mapped[str | None] = mapped_column(Text, nullable=True)
    whatsapp_cobranca_dias_antes: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    whatsapp_cobranca_dias_depois: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    whatsapp_cobranca_modelo: Mapped[str | None] = mapped_column(String(500), nullable=True)
    api_whatsapp: Mapped[str | None] = mapped_column(String(120), nullable=True)
    usuario_api_whatsapp: Mapped[str | None] = mapped_column(String(100), nullable=True)
    token_api_whatsapp: Mapped[str | None] = mapped_column(String(120), nullable=True)
    regra_nono_dig_whats: Mapped[list[dict[str, object]]] = mapped_column(JSON, nullable=False, default=list)
    sufixo_whatsapp: Mapped[str | None] = mapped_column(String(30), nullable=True)
    msg_renovacao: Mapped[str | None] = mapped_column(Text, nullable=True)
    msg_negociacao: Mapped[str | None] = mapped_column(Text, nullable=True)
    pais_whatsapp: Mapped[int] = mapped_column(Integer, nullable=False, default=55)
    msg_campanha: Mapped[str | None] = mapped_column(Text, nullable=True)
    ligar_websocket: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    silenciar_mensagem: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)